services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ghcr.io/basarus/film-react-nest/backend:latest
    container_name: backend
    depends_on:
      - postgres
    networks:
      - backend_network  # Бэкенд остается в своей сети
    env_file:
      - backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ghcr.io/basarus/film-react-nest/frontend:latest
    container_name: frontend
    networks:
      - frontend_network  # Фронтенд в своей сети
    volumes:
      - frontend_dist:/app/dist
    env_file:
      - frontend/.env
    restart: unless-stopped

  postgres:
    image: postgres:14
    container_name: postgres
    networks:
      - backend_network  # PostgreSQL будет в сети бэкенда
    env_file:
      - postgres/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - pgadmin/.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin/data
    ports:
      - 8081:8081
    networks:
      - backend_network  # PgAdmin в сети бэкенда
    depends_on:
      - postgres
    restart: unless-stopped

  nginx:
    image: nginx
    ports:
      - 80:80
    networks:
      - frontend_network  # Nginx в сети фронтенда для обслуживания статики
      - backend_network  # И в сети бэкенда для проксирования запросов
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_dist:/var/www/frontend:rw

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge

volumes:
  pgdata:
  pgadmin-data:
  frontend_dist:
