services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - postgres
    networks:
      - internal
    env_file:
      - backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - internal
    volumes:
      - frontend_dist:/app/dist
    env_file:
      - frontend/.env

  postgres:
    image: postgres:14
    container_name: postgres
    networks:
      - internal
    env_file:
      - postgres/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - pgadmin/.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin/data
    ports:
      - 8080:80
    networks:
      - internal
    depends_on:
      - postgres
    restart: unless-stopped

  nginx:
    image: nginx
    ports:
      - 80:80
    networks:
      - internal
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_dist:/var/www/frontend:ro

networks:
  internal:
    driver: bridge

volumes:
  pgdata:
  pgadmin-data:
  frontend_dist:
